#!/bin/bash

echo "SOURCE_COMMIT: $SOURCE_COMMIT"

if [[ -z "$SOURCE_COMMIT" ]]; then
  export SOURCE_COMMIT="${SOURCE_COMMIT:-$(git rev-parse HEAD)}"
  echo "Updating SOURCE_COMMIT from git rev-parse HEAD"
  echo "SOURCE_COMMIT: $SOURCE_COMMIT"
fi


echo "SOURCE_BRANCH: $SOURCE_BRANCH"

if [[ -z "$SOURCE_BRANCH" ]]; then
  export SOURCE_BRANCH="${SOURCE_BRANCH:-$(git branch --show-current)}"
  echo "Updating SOURCE_BRANCH from git branch --show-current"
  echo "SOURCE_BRANCH: $SOURCE_BRANCH"
fi

echo "DOCKER_TAG: $DOCKER_TAG"

docker build --build-arg SOURCE_COMMIT="$SOURCE_COMMIT" --build-arg SOURCE_BRANCH="$SOURCE_BRANCH" -f $DOCKERFILE_PATH -t $IMAGE_NAME .
